stages:
  - deploy

prod_deploy:
  stage: deploy
  only:
    - staging

  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$PROD_SERVER_SSH" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - |
      if [ -f .env ]; then
        echo ".env file found. Aborting deployment.";
        exit 1;
      fi

      ssh $SSH_USER@$PROD_SERVER "
        cd $WORK_DIR && 
        git pull &&
        npm install &&
        sudo pm2 reload lead-be
      "
